apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    editable: false
    jsonData:
      derivedFields:
        # Trace-link from log to future Tempo/Jaeger if added
        - name: request_id
          matcherRegex: '"request_id":"(\w+)"'
          url: ""
