apiVersion: v2
name: claims-system
description: Insurance Claims Processing System
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - claims
  - insurance
  - healthcare
maintainers:
  - name: Sumit Kumar Mallick
    email: sumit@foliumlabs.net
